//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1111 with alias "captionedImagesContent"
	/// <summary>{Captioned Images Content}</summary>
	public partial interface ICaptionedImagesContent : IPublishedContent
	{
		/// <summary>Content</summary>
		string Content { get; }

		/// <summary>Images</summary>
		IEnumerable<IPublishedContent> Images { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>{Captioned Images Content}</summary>
	[PublishedContentModel("captionedImagesContent")]
	public partial class CaptionedImagesContent : PublishedContentModel, ICaptionedImagesContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "captionedImagesContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public CaptionedImagesContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CaptionedImagesContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return GetContent(this); }
		}

		/// <summary>Static getter for Content</summary>
		public static string GetContent(ICaptionedImagesContent that) { return that.GetPropertyValue<string>("content"); }

		///<summary>
		/// Images
		///</summary>
		[ImplementPropertyType("images")]
		public IEnumerable<IPublishedContent> Images
		{
			get { return GetImages(this); }
		}

		/// <summary>Static getter for Images</summary>
		public static IEnumerable<IPublishedContent> GetImages(ICaptionedImagesContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("images"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(ICaptionedImagesContent that) { return that.GetPropertyValue<string>("title"); }
	}
}
