//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1259 with alias "footerBasicContent"
	/// <summary>{Footer Basic Content}</summary>
	public partial interface IFooterBasicContent : IPublishedContent
	{
		/// <summary>Copyright</summary>
		string Copyright { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>{Footer Basic Content}</summary>
	[PublishedContentModel("footerBasicContent")]
	public partial class FooterBasicContent : PublishedContentModel, IFooterBasicContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerBasicContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterBasicContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterBasicContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Copyright
		///</summary>
		[ImplementPropertyType("copyright")]
		public string Copyright
		{
			get { return GetCopyright(this); }
		}

		/// <summary>Static getter for Copyright</summary>
		public static string GetCopyright(IFooterBasicContent that) { return that.GetPropertyValue<string>("copyright"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(IFooterBasicContent that) { return that.GetPropertyValue<string>("title"); }
	}
}
