//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1258 with alias "footerNavigationContent"
	/// <summary>{Footer Navigation Content}</summary>
	public partial interface IFooterNavigationContent : IPublishedContent
	{
		/// <summary>Navigation</summary>
		IEnumerable<IPublishedContent> Navigation { get; }
	}

	/// <summary>{Footer Navigation Content}</summary>
	[PublishedContentModel("footerNavigationContent")]
	public partial class FooterNavigationContent : PublishedContentModel, IFooterNavigationContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "footerNavigationContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FooterNavigationContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FooterNavigationContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Navigation
		///</summary>
		[ImplementPropertyType("navigation")]
		public IEnumerable<IPublishedContent> Navigation
		{
			get { return GetNavigation(this); }
		}

		/// <summary>Static getter for Navigation</summary>
		public static IEnumerable<IPublishedContent> GetNavigation(IFooterNavigationContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navigation"); }
	}
}
