//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1267 with alias "headerLinkContent"
	/// <summary>{Header Link Content}</summary>
	public partial interface IHeaderLinkContent : IPublishedContent
	{
		/// <summary>Link</summary>
		RJP.MultiUrlPicker.Models.Link Link { get; }
	}

	/// <summary>{Header Link Content}</summary>
	[PublishedContentModel("headerLinkContent")]
	public partial class HeaderLinkContent : PublishedContentModel, IHeaderLinkContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "headerLinkContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeaderLinkContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeaderLinkContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public RJP.MultiUrlPicker.Models.Link Link
		{
			get { return GetLink(this); }
		}

		/// <summary>Static getter for Link</summary>
		public static RJP.MultiUrlPicker.Models.Link GetLink(IHeaderLinkContent that) { return that.GetPropertyValue<RJP.MultiUrlPicker.Models.Link>("link"); }
	}
}
