//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	/// <summary>Header - Bar Info</summary>
	[PublishedContentModel("headerStandardBarWInfo")]
	public partial class HeaderStandardBarWinfo : PublishedContentModel, IHeaderInfoContent, IHeaderLinkContent, IHeaderNavigationContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "headerStandardBarWInfo";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeaderStandardBarWinfo(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeaderStandardBarWinfo, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return MBran.Modules.HeaderInfoContent.GetAddress(this); }
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return MBran.Modules.HeaderInfoContent.GetEmail(this); }
		}

		///<summary>
		/// Link
		///</summary>
		[ImplementPropertyType("link")]
		public RJP.MultiUrlPicker.Models.Link Link
		{
			get { return MBran.Modules.HeaderLinkContent.GetLink(this); }
		}

		///<summary>
		/// Navigation
		///</summary>
		[ImplementPropertyType("navigation")]
		public IEnumerable<IPublishedContent> Navigation
		{
			get { return MBran.Modules.HeaderNavigationContent.GetNavigation(this); }
		}
	}
}
