//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1253 with alias "headerInfoContent"
	/// <summary>{Header Info Content}</summary>
	public partial interface IHeaderInfoContent : IPublishedContent
	{
		/// <summary>Address</summary>
		string Address { get; }

		/// <summary>Email</summary>
		string Email { get; }
	}

	/// <summary>{Header Info Content}</summary>
	[PublishedContentModel("headerInfoContent")]
	public partial class HeaderInfoContent : PublishedContentModel, IHeaderInfoContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "headerInfoContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HeaderInfoContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HeaderInfoContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return GetAddress(this); }
		}

		/// <summary>Static getter for Address</summary>
		public static string GetAddress(IHeaderInfoContent that) { return that.GetPropertyValue<string>("address"); }

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return GetEmail(this); }
		}

		/// <summary>Static getter for Email</summary>
		public static string GetEmail(IHeaderInfoContent that) { return that.GetPropertyValue<string>("email"); }
	}
}
