//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	/// <summary>Nav - Two Level Dropdown</summary>
	[PublishedContentModel("navigationTwoLevelDropdown")]
	public partial class NavigationTwoLevelDropdown : PublishedContentModel, IModuleContent, INavigationContent, INavigationMultiContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationTwoLevelDropdown";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationTwoLevelDropdown(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationTwoLevelDropdown, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Enable?
		///</summary>
		[ImplementPropertyType("enable")]
		public bool Enable
		{
			get { return MBran.Modules.ModuleContent.GetEnable(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return MBran.Modules.NavigationContent.GetTitle(this); }
		}

		///<summary>
		/// Navigration Groups
		///</summary>
		[ImplementPropertyType("navigrationGroups")]
		public IEnumerable<IPublishedContent> NavigrationGroups
		{
			get { return MBran.Modules.NavigationMultiContent.GetNavigrationGroups(this); }
		}
	}
}
