//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1184 with alias "navigationGroupContent"
	/// <summary>{Navigation Group Content}</summary>
	public partial interface INavigationGroupContent : IPublishedContent
	{
		/// <summary>Links</summary>
		IEnumerable<RJP.MultiUrlPicker.Models.Link> Links { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>{Navigation Group Content}</summary>
	[PublishedContentModel("navigationGroupContent")]
	public partial class NavigationGroupContent : PublishedContentModel, INavigationGroupContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "navigationGroupContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NavigationGroupContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NavigationGroupContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Links
		///</summary>
		[ImplementPropertyType("links")]
		public IEnumerable<RJP.MultiUrlPicker.Models.Link> Links
		{
			get { return GetLinks(this); }
		}

		/// <summary>Static getter for Links</summary>
		public static IEnumerable<RJP.MultiUrlPicker.Models.Link> GetLinks(INavigationGroupContent that) { return that.GetPropertyValue<IEnumerable<RJP.MultiUrlPicker.Models.Link>>("links"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(INavigationGroupContent that) { return that.GetPropertyValue<string>("title"); }
	}
}
