//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1219 with alias "pageNavigationContent"
	/// <summary>{Page Navigation Content}</summary>
	public partial interface IPageNavigationContent : IPublishedContent
	{
		/// <summary>Footer</summary>
		IEnumerable<IPublishedContent> NavigationFooter { get; }

		/// <summary>Header</summary>
		IEnumerable<IPublishedContent> NavigationHeader { get; }
	}

	/// <summary>{Page Navigation Content}</summary>
	[PublishedContentModel("pageNavigationContent")]
	public partial class PageNavigationContent : PublishedContentModel, IPageNavigationContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageNavigationContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageNavigationContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageNavigationContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer
		///</summary>
		[ImplementPropertyType("navigationFooter")]
		public IEnumerable<IPublishedContent> NavigationFooter
		{
			get { return GetNavigationFooter(this); }
		}

		/// <summary>Static getter for Footer</summary>
		public static IEnumerable<IPublishedContent> GetNavigationFooter(IPageNavigationContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationFooter"); }

		///<summary>
		/// Header
		///</summary>
		[ImplementPropertyType("navigationHeader")]
		public IEnumerable<IPublishedContent> NavigationHeader
		{
			get { return GetNavigationHeader(this); }
		}

		/// <summary>Static getter for Header</summary>
		public static IEnumerable<IPublishedContent> GetNavigationHeader(IPageNavigationContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("navigationHeader"); }
	}
}
