//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1255 with alias "siteBasicModules"
	/// <summary>{Site Basic Modules}</summary>
	public partial interface ISiteBasicModules : IPublishedContent
	{
		/// <summary>Footer Modules</summary>
		IEnumerable<IPublishedContent> FooterModules { get; }

		/// <summary>Header Modules</summary>
		IEnumerable<IPublishedContent> HeaderModules { get; }
	}

	/// <summary>{Site Basic Modules}</summary>
	[PublishedContentModel("siteBasicModules")]
	public partial class SiteBasicModules : PublishedContentModel, ISiteBasicModules
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "siteBasicModules";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SiteBasicModules(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SiteBasicModules, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Footer Modules
		///</summary>
		[ImplementPropertyType("footerModules")]
		public IEnumerable<IPublishedContent> FooterModules
		{
			get { return GetFooterModules(this); }
		}

		/// <summary>Static getter for Footer Modules</summary>
		public static IEnumerable<IPublishedContent> GetFooterModules(ISiteBasicModules that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("footerModules"); }

		///<summary>
		/// Header Modules
		///</summary>
		[ImplementPropertyType("headerModules")]
		public IEnumerable<IPublishedContent> HeaderModules
		{
			get { return GetHeaderModules(this); }
		}

		/// <summary>Static getter for Header Modules</summary>
		public static IEnumerable<IPublishedContent> GetHeaderModules(ISiteBasicModules that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("headerModules"); }
	}
}
