//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1218 with alias "siteBasicContent"
	/// <summary>{Site Basic Content}</summary>
	public partial interface ISiteBasicContent : IPublishedContent
	{
		/// <summary>Email</summary>
		string Email { get; }

		/// <summary>Logo</summary>
		IPublishedContent Logo { get; }

		/// <summary>Phone</summary>
		string Phone { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>{Site Basic Content}</summary>
	[PublishedContentModel("siteBasicContent")]
	public partial class SiteBasicContent : PublishedContentModel, ISiteBasicContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "siteBasicContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SiteBasicContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SiteBasicContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return GetEmail(this); }
		}

		/// <summary>Static getter for Email</summary>
		public static string GetEmail(ISiteBasicContent that) { return that.GetPropertyValue<string>("email"); }

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return GetLogo(this); }
		}

		/// <summary>Static getter for Logo</summary>
		public static IPublishedContent GetLogo(ISiteBasicContent that) { return that.GetPropertyValue<IPublishedContent>("logo"); }

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return GetPhone(this); }
		}

		/// <summary>Static getter for Phone</summary>
		public static string GetPhone(ISiteBasicContent that) { return that.GetPropertyValue<string>("phone"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(ISiteBasicContent that) { return that.GetPropertyValue<string>("title"); }
	}
}
