//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	/// <summary>Site Config</summary>
	[PublishedContentModel("siteConfig")]
	public partial class SiteConfig : PublishedContentModel, ISiteBasicContent, ISiteBasicModules, ISiteSocialContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "siteConfig";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SiteConfig(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SiteConfig, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Email
		///</summary>
		[ImplementPropertyType("email")]
		public string Email
		{
			get { return MBran.Modules.SiteBasicContent.GetEmail(this); }
		}

		///<summary>
		/// Logo
		///</summary>
		[ImplementPropertyType("logo")]
		public IPublishedContent Logo
		{
			get { return MBran.Modules.SiteBasicContent.GetLogo(this); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return MBran.Modules.SiteBasicContent.GetPhone(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return MBran.Modules.SiteBasicContent.GetTitle(this); }
		}

		///<summary>
		/// Footer Modules
		///</summary>
		[ImplementPropertyType("footerModules")]
		public IEnumerable<IPublishedContent> FooterModules
		{
			get { return MBran.Modules.SiteBasicModules.GetFooterModules(this); }
		}

		///<summary>
		/// Header Modules
		///</summary>
		[ImplementPropertyType("headerModules")]
		public IEnumerable<IPublishedContent> HeaderModules
		{
			get { return MBran.Modules.SiteBasicModules.GetHeaderModules(this); }
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return MBran.Modules.SiteSocialContent.GetFacebook(this); }
		}

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return MBran.Modules.SiteSocialContent.GetInstagram(this); }
		}

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return MBran.Modules.SiteSocialContent.GetTwitter(this); }
		}

		///<summary>
		/// Youtube
		///</summary>
		[ImplementPropertyType("youtube")]
		public string Youtube
		{
			get { return MBran.Modules.SiteSocialContent.GetYoutube(this); }
		}
	}
}
