//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1256 with alias "siteSocialContent"
	/// <summary>{Site Social Content}</summary>
	public partial interface ISiteSocialContent : IPublishedContent
	{
		/// <summary>Facebook</summary>
		string Facebook { get; }

		/// <summary>Instagram</summary>
		string Instagram { get; }

		/// <summary>Twitter</summary>
		string Twitter { get; }

		/// <summary>Youtube</summary>
		string Youtube { get; }
	}

	/// <summary>{Site Social Content}</summary>
	[PublishedContentModel("siteSocialContent")]
	public partial class SiteSocialContent : PublishedContentModel, ISiteSocialContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "siteSocialContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SiteSocialContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SiteSocialContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Facebook
		///</summary>
		[ImplementPropertyType("facebook")]
		public string Facebook
		{
			get { return GetFacebook(this); }
		}

		/// <summary>Static getter for Facebook</summary>
		public static string GetFacebook(ISiteSocialContent that) { return that.GetPropertyValue<string>("facebook"); }

		///<summary>
		/// Instagram
		///</summary>
		[ImplementPropertyType("instagram")]
		public string Instagram
		{
			get { return GetInstagram(this); }
		}

		/// <summary>Static getter for Instagram</summary>
		public static string GetInstagram(ISiteSocialContent that) { return that.GetPropertyValue<string>("instagram"); }

		///<summary>
		/// Twitter
		///</summary>
		[ImplementPropertyType("twitter")]
		public string Twitter
		{
			get { return GetTwitter(this); }
		}

		/// <summary>Static getter for Twitter</summary>
		public static string GetTwitter(ISiteSocialContent that) { return that.GetPropertyValue<string>("twitter"); }

		///<summary>
		/// Youtube
		///</summary>
		[ImplementPropertyType("youtube")]
		public string Youtube
		{
			get { return GetYoutube(this); }
		}

		/// <summary>Static getter for Youtube</summary>
		public static string GetYoutube(ISiteSocialContent that) { return that.GetPropertyValue<string>("youtube"); }
	}
}
