//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Testimonial Item</summary>
	[PublishedContentModel("testimonialItem")]
	public partial class TestimonialItem : PublishedContentModel, IModuleContent, ITestimonialItemContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "testimonialItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TestimonialItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TestimonialItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Enable?
		///</summary>
		[ImplementPropertyType("enable")]
		public bool Enable
		{
			get { return Umbraco.Web.PublishedContentModels.ModuleContent.GetEnable(this); }
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return Umbraco.Web.PublishedContentModels.TestimonialItemContent.GetContent(this); }
		}

		///<summary>
		/// Display Name
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return Umbraco.Web.PublishedContentModels.TestimonialItemContent.GetDisplayName(this); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return Umbraco.Web.PublishedContentModels.TestimonialItemContent.GetImage(this); }
		}

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return Umbraco.Web.PublishedContentModels.TestimonialItemContent.GetJobTitle(this); }
		}
	}
}
