//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace MBran.Modules
{
	// Mixin content Type 1172 with alias "testimonialItemContent"
	/// <summary>{Testimonial Item Content}</summary>
	public partial interface ITestimonialItemContent : IPublishedContent
	{
		/// <summary>Content</summary>
		string Content { get; }

		/// <summary>Display Name</summary>
		string DisplayName { get; }

		/// <summary>Image</summary>
		IPublishedContent Image { get; }

		/// <summary>Job Title</summary>
		string JobTitle { get; }
	}

	/// <summary>{Testimonial Item Content}</summary>
	[PublishedContentModel("testimonialItemContent")]
	public partial class TestimonialItemContent : PublishedContentModel, ITestimonialItemContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "testimonialItemContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TestimonialItemContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TestimonialItemContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return GetContent(this); }
		}

		/// <summary>Static getter for Content</summary>
		public static string GetContent(ITestimonialItemContent that) { return that.GetPropertyValue<string>("content"); }

		///<summary>
		/// Display Name
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return GetDisplayName(this); }
		}

		/// <summary>Static getter for Display Name</summary>
		public static string GetDisplayName(ITestimonialItemContent that) { return that.GetPropertyValue<string>("displayName"); }

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return GetImage(this); }
		}

		/// <summary>Static getter for Image</summary>
		public static IPublishedContent GetImage(ITestimonialItemContent that) { return that.GetPropertyValue<IPublishedContent>("image"); }

		///<summary>
		/// Job Title
		///</summary>
		[ImplementPropertyType("jobTitle")]
		public string JobTitle
		{
			get { return GetJobTitle(this); }
		}

		/// <summary>Static getter for Job Title</summary>
		public static string GetJobTitle(ITestimonialItemContent that) { return that.GetPropertyValue<string>("jobTitle"); }
	}
}
