//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1177 with alias "formTextAndImageContent"
	/// <summary>{Form Text and Image Content}</summary>
	public partial interface IFormTextAndImageContent : IPublishedContent
	{
		/// <summary>Content</summary>
		string Content { get; }

		/// <summary>Image</summary>
		IPublishedContent Image { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>{Form Text and Image Content}</summary>
	[PublishedContentModel("formTextAndImageContent")]
	public partial class FormTextAndImageContent : PublishedContentModel, IFormTextAndImageContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "formTextAndImageContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public FormTextAndImageContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FormTextAndImageContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return GetContent(this); }
		}

		/// <summary>Static getter for Content</summary>
		public static string GetContent(IFormTextAndImageContent that) { return that.GetPropertyValue<string>("content"); }

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public IPublishedContent Image
		{
			get { return GetImage(this); }
		}

		/// <summary>Static getter for Image</summary>
		public static IPublishedContent GetImage(IFormTextAndImageContent that) { return that.GetPropertyValue<IPublishedContent>("image"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(IFormTextAndImageContent that) { return that.GetPropertyValue<string>("title"); }
	}
}
