//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1162 with alias "tabsContent"
	/// <summary>{Tabs Content}</summary>
	public partial interface ITabsContent : IPublishedContent
	{
		/// <summary>Modules</summary>
		IEnumerable<IPublishedContent> Modules { get; }

		/// <summary>Title</summary>
		string Title { get; }
	}

	/// <summary>{Tabs Content}</summary>
	[PublishedContentModel("tabsContent")]
	public partial class TabsContent : PublishedContentModel, ITabsContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "tabsContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TabsContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TabsContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Modules
		///</summary>
		[ImplementPropertyType("modules")]
		public IEnumerable<IPublishedContent> Modules
		{
			get { return GetModules(this); }
		}

		/// <summary>Static getter for Modules</summary>
		public static IEnumerable<IPublishedContent> GetModules(ITabsContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("modules"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("title")]
		public string Title
		{
			get { return GetTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetTitle(ITabsContent that) { return that.GetPropertyValue<string>("title"); }
	}
}
