//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	// Mixin content Type 1181 with alias "testimonialListingContent"
	/// <summary>{Testimonial Listing Content}</summary>
	public partial interface ITestimonialListingContent : IPublishedContent
	{
		/// <summary>Testimonials</summary>
		IEnumerable<IPublishedContent> Testimonials { get; }
	}

	/// <summary>{Testimonial Listing Content}</summary>
	[PublishedContentModel("testimonialListingContent")]
	public partial class TestimonialListingContent : PublishedContentModel, ITestimonialListingContent
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "testimonialListingContent";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public TestimonialListingContent(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<TestimonialListingContent, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Testimonials
		///</summary>
		[ImplementPropertyType("testimonials")]
		public IEnumerable<IPublishedContent> Testimonials
		{
			get { return GetTestimonials(this); }
		}

		/// <summary>Static getter for Testimonials</summary>
		public static IEnumerable<IPublishedContent> GetTestimonials(ITestimonialListingContent that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("testimonials"); }
	}
}
